Fix Github Workflow Test Issue (#731)
Following the modification of the entry-point, the default shell
changed. Instead of using bash we are now using sh (dash). The special
flag failpipe is not supported and then, the latest command to be
executed in a pipe is valid if it does not fail.

Created a canary test in the pipeline that always fail to avoid
this kind of issue in the future.

github_workflow.sh script has been rollbacked. The new entry-point
was not correctly working with it.

see: https://github.com/ArweaveTeam/arweave-dev/issues/816

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -151,11 +151,48 @@ jobs:
             apps.tar.gz
 
   ####################################################################
+  # Canary testing, should fail.
+  ####################################################################
+  canary:
+    needs: build
+    runs-on: self-hosted
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: "recursive"
+
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: build-${{ github.sha }}
+
+      # Both artifacts (_build and apps dir) are
+      # required.
+      - name: Extract artifact
+        run: |
+          tar zxfp _build.tar.gz
+          tar zxfp apps.tar.gz
+
+      - id: canary
+        name: ar_canary.erl
+        continue-on-error: true
+        run: bash scripts/github_workflow.sh "tests" "ar_canary"
+
+      - name: should fail
+        run: |
+          if test "${{ steps.canary.outcome }}" = "failure"
+          then
+            exit 0
+          else
+            exit 1
+          fi
+
+  ####################################################################
   # Long-running tests. Put these first to limit the overall runtime
   # of the test suite
   ####################################################################
   eunit-tests-long-running:
-    needs: build
+    needs: canary
     runs-on: self-hosted
     strategy:
       max-parallel: 4
@@ -192,7 +229,7 @@ jobs:
 
       - name: ${{ matrix.core_test_mod }}.erl
         id: tests
-        run: bash scripts/github_workflow.sh "test" "${{ matrix.core_test_mod }}"
+        run: bash scripts/github_workflow.sh "tests" "${{ matrix.core_test_mod }}"
 
       # this part of the job produces test artifacts from logs
       # generated by the tests. It also collect dumps and the files
@@ -214,7 +251,7 @@ jobs:
   # Modules containing tests
   ####################################################################
   eunit-tests-modules:
-    needs: build
+    needs: canary
     runs-on: self-hosted
     strategy:
       max-parallel: 4
@@ -285,7 +322,7 @@ jobs:
 
       - name: ${{ matrix.core_test_mod }}.erl
         id: tests
-        run: bash scripts/github_workflow.sh "test" "${{ matrix.core_test_mod }}"
+        run: bash scripts/github_workflow.sh "tests" "${{ matrix.core_test_mod }}"
 
       # this part of the job produces test artifacts from logs
       # generated by the tests. It also collect dumps and the files
@@ -308,7 +345,7 @@ jobs:
   # prefix name
   ####################################################################
   eunit-tests-suite:
-    needs: build
+    needs: canary
     runs-on: self-hosted
     strategy:
       max-parallel: 4
@@ -353,7 +390,7 @@ jobs:
 
       - name: ${{ matrix.core_test_mod }}.erl
         id: tests
-        run: bash scripts/github_workflow.sh "test" "${{ matrix.core_test_mod }}"
+        run: bash scripts/github_workflow.sh "tests" "${{ matrix.core_test_mod }}"
 
       # this part of the job produces test artifacts from logs
       # generated by the tests. It also collect dumps and the files
