Bug fixes for VDF client/server communication. 1. Fix serialization/deserialization logic 2. Server pushes format 1 updates by default, and updated client will detect the format error and request, via nonce_limiter_update_response, a different format. Server will then cache that new forma value and push updates to that peer in teh future using the new format

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -117,6 +117,8 @@ jobs:
       - name: ${{ matrix.core_test_mod }}.erl
         run: |
           set -e
+          set -o pipefail
+          rm -f *.out || true
           EXIT_CODE=0
           echo -e "\033[0;32m===> Running tests...\033[0m"
           export PATH=$(pwd)/_build/erts/bin:$PATH
@@ -127,32 +129,37 @@ jobs:
             RETRYABLE=0
             erl $ERL_TEST_OPTS -noshell -name ${{ matrix.core_test_mod }}@127.0.0.1 -setcookie ${{ matrix.core_test_mod }} -run ar tests "${{ matrix.core_test_mod }}" -s init stop 2>&1 | tee master.out &
             ERL_MASTER_PID=$! # capture PID of the master background process
-            wait $ERL_MASTER_PID || EXIT_CODE=$?
+            wait $ERL_MASTER_PID
+            EXIT_CODE=$?
             kill -9 $ERL_MASTER_PID > /dev/null 2>&1 || true
             # For debugging purposes, print the slave output if the tests failed
             if [[ $EXIT_CODE -ne 0 ]]; then
-              if [[ -e slave.out ]]; then
+              if compgen -G "slave.out" > /dev/null; then
                 first_line_slave=$(head -n 1 slave.out)
-                first_line_master=$(head -n 1 master.out)
-                # Check if it is a retryable error
-                if [[ "$first_line_slave" == "Protocol 'inet_tcp': register/listen error: "* ]]; then
-                  echo "Retrying test because of inet_tcp error..."
-                  RETRYABLE=1
-                  sleep 1
-                elif [[ "$first_line_slave" == "Protocol 'inet_tcp': the name"* ]]; then
-                  echo "Retrying test because of inet_tcp clash..."
-                  RETRYABLE=1
-                  sleep 1
-                elif [[ "$first_line_master" == "econnrefused"* ]]; then
-                  echo "Retrying test because of econnrefused..."
-                  RETRYABLE=1
-                  sleep 1
-                else
+              else
+                first_line_slave=""
+              fi
+              first_line_master=$(head -n 1 master.out)
+              # Check if it is a retryable error
+              if [[ "$first_line_slave" == "Protocol 'inet_tcp': register/listen error: "* ]]; then
+                echo "Retrying test because of inet_tcp error..."
+                RETRYABLE=1
+                sleep 1
+              elif [[ "$first_line_slave" == "Protocol 'inet_tcp': the name"* ]]; then
+                echo "Retrying test because of inet_tcp clash..."
+                RETRYABLE=1
+                sleep 1
+              elif [[ "$first_line_master" == *"econnrefused"* ]]; then
+                echo "Retrying test because of econnrefused..."
+                RETRYABLE=1
+                sleep 1
+              else
+                if compgen -G slave.out > /dev/null; then
                   echo -e "\033[0;31m===> Test failed, printing the slave node's output...\033[0m"
                   cat slave.out
+                else
+                  echo -e "\033[0;31m===> Test failed without slave output...\033[0m"
                 fi
-              else
-                echo -e "\033[0;31m===> Test failed without slave output...\033[0m"
               fi
             fi
           done
